### ISSUE TITLE
python3 main.py throws error on experimental branch

### ISSUE THREAD

**Issue by samundra** [foss-np/anubad#13]
output of `python3 main.py`

```
Traceback (most recent call last):
  File "main.py", line 32, in <module>
    import ui.home
  File "/home/developer/personal/anubad/src/ui/home.py", line 18, in <module>
    import _searchbar
  File "/home/developer/personal/anubad/src/ui/_searchbar.py", line 108, in <module>
    class INavHistory(Gtk.Popover):
  File "/usr/lib/python3/dist-packages/gi/module.py", line 320, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python3/dist-packages/gi/module.py", line 139, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.Gtk' object has no attribute 'Popover'
```

**Comment by rhoit** [comment]
I guess `Gtk.Popover()` was release in version 3.12 which version are you using?

`PopOver` is used for **reverse-i-search** as show below.

![screenshot131](https://cloud.githubusercontent.com/assets/1684754/16720211/8f0028ac-4753-11e6-9df8-8d880eb03e6b.png)

I guess you will also have the issue of theme too, since we have move the anubad layout completely in CSS, all font UI alignment is handled by it.

In GTK 3.18 many thing in CSS have changed.

**Comment by rhoit** [comment]
I guess we need the downgrade code to keep up with distributions now, what do you thing @samundra since people will be still using old things. @zerOnepal now things are under fire.

**Comment by samundra** [comment]
> I guess we need the downgrade code to keep up with distributions now

@rhoit Maybe we need to bump up the Major version with breaking changes. That way we don't have to maintain the breaking changes. Regarding the support we can continue support on different branch probably the one we are using. 

> I guess Gtk.Popover() was release in version 3.12 which version are you using?

My current Gtk version seems to be 3.10.8-0ubuntu1.6. I think I will stick to the current version until I find myself with enough time for experiments :smile:

**Comment by rhoit** [comment]
run =make gtk-lt-12-patch= in =src/= path doesn't fix everything but tries to run it without error.
